# Generated by Django 4.1.7 on 2023-02-23 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_expiringlink_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expire_after',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
