# Generated by Django 4.1.7 on 2023-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='images.thumbnail'),
        ),
    ]
